### ISSUE TITLE
Provide functionality to play/pause with spacebar

### ISSUE THREAD

**Issue by foolmarshal** [foolmarshal/Audify#2]
Provide functionality to play/pause with spacebar

**Comment by Gowrishankar04** [comment]
Hi @foolmarshal,

Can you please assign this to me?

Thanks

**Comment by foolmarshal** [comment]
Sure, Assigning this issue to @Gowrishankar04

**Comment by Gowrishankar04** [comment]
Hi @foolmarshal , Can you please add [hacktoberfest-accepted] tag to the pr. It is showing not-participating in hacktoberfest.

Thanks

**Comment by foolmarshal** [comment]
@Gowrishankar04 **hacktoberfest-accepted** tag is already there.

Can you pls check once again on the Hacktoberfest website, bcz it generally takes sometime in updating there.

**Comment by Gowrishankar04** [comment]
@foolmarshal - Updated Thanks
