### ISSUE TITLE
Progress bar is inaccurate when play/paused by clicking songItem

### ISSUE THREAD

**Issue by foolmarshal** [foolmarshal/Audify#9]
Progress bar is inaccurate when play/paused by clicking songItem.

When paused a song by clicking on songItem, the progress bar goes to random position.

Need to fix this.

**Comment by mad-alpha** [comment]
Hello Sir,

Please assign this issue to me.

**Comment by foolmarshal** [comment]
Assigning this issue to @mad-alpha
